stages:
  - build
  - test
  - publish

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

variables:
  DOCKER_PROXY: docker-ext.artifactory.bluecatlabs.net
  NODE_IMAGE: $DOCKER_PROXY/node:lts-alpine

install:
  stage: .pre
  image: $NODE_IMAGE
  script:
    - npm run init-scope
    - npm run set-token
    - npm run fix-auth
    - npm ci --cache .npm --prefer-offline
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

build:
  stage: build
  image: $NODE_IMAGE
  script:
    - npm run build-storybook
  needs:
    - install
  artifacts:
    when: always
    paths:
      - .out/

test:unit:
  stage: test
  image: $NODE_IMAGE
  script:
    - npm run test-ci
  variables:
    TZ: America/Toronto
  needs:
    - install
  allow_failure:
    exit_codes: 1
  artifacts:
    when: always
    reports:
      junit: build/junit.xml
      cobertura: coverage/cobertura-coverage.xml

publish:ui:
  stage: publish
  image: docker-dev.artifactory.bluecatlabs.net/ui/aws-s3:1.0.0
  environment:
    name: storybook
    url: https://storybook.dnsedge.tools
  script:
    - aws-s3 -r aws/user/sts/ui-storybook sync -c cache-rules.json .out s3://storybook.dnsedge.tools
  variables:
    AWS_REGION: us-west-2
  needs:
    - build
