export {default as circleInfoOutline} from './circleInfoOutline';
/** @deprecated use circleInfoOutline instead. */
export {default as infoCircleOutline} from './circleInfoOutline';
export {default as rhombusExclamation} from './rhombusExclamation';
/** @deprecated use rhombusExclamation instead. */
export {default as exclamationRhombus} from './rhombusExclamation';
export {default as xmarkThin} from './xmarkThin';
/** @deprecated use xmarkThin instead. */
export {default as timesThin} from './xmarkThin';
