#! /bin/sh

update() {
	git diff --quiet --cached "packages/pelagos/defs/$1.yaml" && return 0
	node "packages/pelagos/scripts/update-$1" && git add "packages/pelagos/less/$1.less"
}

update breakpoints
update colors
update elevations
update fonts
update shadows
update spacing
update themes

node packages/pelagos/scripts/update-docs
