#! /bin/sh
git diff --quiet --cached packages/pelagos/defs/colors.yaml || (npm -w packages/pelagos run update-colors && git add packages/pelagos/less/colors.less)
git diff --quiet --cached packages/pelagos/defs/elevations.yaml || (npm -w packages/pelagos run update-elevations && git add packages/pelagos/less/elevations.less)
git diff --quiet --cached packages/pelagos/defs/fonts.yaml || (npm -w packages/pelagos run update-fonts && git add packages/pelagos/less/fonts.less)
git diff --quiet --cached packages/pelagos/defs/shadows.yaml || (npm -w packages/pelagos run update-shadows && git add packages/pelagos/less/shadows.less)
git diff --quiet --cached packages/pelagos/defs/spacing.yaml || (npm -w packages/pelagos run update-spacing && git add packages/pelagos/less/spacing.less)
git diff --quiet --cached packages/pelagos/defs/themes.yaml || (npm -w packages/pelagos run update-themes && git add packages/pelagos/less/themes.less)
