name: Chromatic

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # tag=v6.3.0
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm ci
          npx lerna run prepack

      - name: Publish to Chromatic
        uses: chromaui/action@8a2b82547aef5a3efc8ec3c7905f4ab09a76ed0b # tag=v16.1.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
