name: Chromatic

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # tag=v7.1.0
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm ci
          npx lerna run prepack

      - name: Publish to Chromatic
        uses: chromaui/action@38afd264ef2241136f12d039093c2724748bec08 # tag=v18.11.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
