name: ESLint

on:
  push:
    branches: ['*']

permissions: read-all

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1

      - name: Setup node
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # tag=v7.1.0
        with:
          node-version: 24

      - name: Run ESLint
        run: |
          npm ci
          npm run lint-ci
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # tag=v4.38.3
        with:
          sarif_file: build/eslint-results.sarif
          wait-for-processing: true
